### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by idf** [bamos/latex-templates#6]
In http://bamos.github.io/latex-templates/, some links are broken like the "source" link https://github.com/bamos/latex-templates/tree/master/templates/cheatsheet

**Comment by bamos** [comment]
Thanks for the report @idf - I refactored this a while ago in https://github.com/bamos/latex-templates/commit/5a51b3db4c43b7dfba1469b8dc7c5d850bc0bcc4 and forgot to regenerate the static site. Fixed!

I also just added this and all of my other github pages to my nightly bad link checker.
