### ISSUE TITLE
error with latest version of BibTexParser

### ISSUE THREAD

**Issue by EmanueleCannizzaro** [bamos/latex-templates#8]
when executing the script with python 3.10 I get the following error message:

(py310) emanuele@developer:/data/git/pycvcl/cv$ make
./generate.py cv.yaml
Processing section: about
Processing section: current_position
Processing section: education
Processing section: positions
Processing section: honors
Processing section: all_publications
Traceback (most recent call last):
  File "./generate.py", line 624, in <module>
    main()
  File "./generate.py", line 619, in main
    process_resume(LATEX_CONTEXT, yaml_data, args.preview)
  File "./generate.py", line 586, in process_resume
    rendered_resume = context.render_resume(yaml_data)
  File "./generate.py", line 500, in render_resume
    section_data['content'] = get_pub_latex(self, section_content)
  File "./generate.py", line 332, in get_pub_latex
    pubs = load_and_replace(config['file'])
  File "./generate.py", line 320, in load_and_replace
    parser = BibTexParser(f.read(), bc.author).get_entry_list()
TypeError: BibTexParser.__new__() takes from 1 to 2 positional arguments but 3 were given
make: *** [Makefile:35: build/cv.tex] Error 1

I suspect is a change in the package API.

Can you please look into it?

Thank you

**Comment by bamos** [comment]
Should this be an issue in https://github.com/bamos/cv instead?  And can you try with bibtexparser version 0.6.2? That's what I'm currently using
